from django.urls import path

from Users import context_processors
from . import views

urlpatterns = [
    path('home/',views.index,name='index'),
    # path('index/',views.homepage,name='home'),
    path('customers/', views.customers_list,name='customers'),
    path('customers/registeration/', views.customer_registration,name='customer_register'),
    path('customers/update/<int:id>/', views.customer_update,name='customer_update'),
    path('suppliers/', views.suppliers_list,name='suppliers_list'),
    path('suppliers/registeration/', views.supplier_registration,name='supplier_register'),
    path('supplier/update/<int:id>/', views.supplier_update, name='supplier_update'),
    path('add-tickets/', views.ticket_register,name='ticket_register'),
    path('tickets/', views.list_tickets,name='list_tickets'),
    path('ticket/update/<int:ticket_id>/', views.update_ticket, name='update_tickets'),
    path('add-city/',views.city_register,name='city_register'),
    path('cities/',views.city_view,name='cities'),
    path('city/update/<int:id>/', views.city_update, name='city_update'),
    path('add-visa-booking/', views.visa_booking_register, name='visa_booking_register'),
    path('visa-bookings/', views.list_visa_bookings,name='visa_bookings_list'),
    path('update-visa-bookings/<int:id>', views.update_visa_booking,name='update_visa_bookings'),
    path('select_customer/', views.select_customer, name='select_customer'),
    path('pending-bookings/Ticket/<int:customer_id>/', views.customer_ticket_pending_bookings, name='customer_ticket_pending_bookings'),
    path('invoices/', views.invoice_list, name='invoice_list'),
    path('invoices/view/<int:invoice_id>/', views.view_invoices, name='view_invoice'),
    path('invoices/edit/<int:transaction_id>/', views.edit_transaction, name='edit_transaction'),
    path('incomplete-transactions/', views.incomplete_transactions, name='incomplete_transactions'),
    path('complete-payment/<int:transaction_id>/', views.complete_payment, name='complete_payment'),
    path('pending-bookings/visa/<int:customer_id>/', views.customer_pending_visa_bookings, name='customer_pending_visa_bookings'),
    path('expenses/',views.expense_list,name='expenses'),
    path('record-expense/',views.record_expense,name='add_expense'),
    path('update-expense/<int:expense_id>/', views.expense_update, name='update_expense'),
    path('add-new-employee/',views.register_employee,name='register_employee'),
    path('employees/',views.employee_list,name='employee_list'),
    path('employee/update/<int:employee_id>',views.employee_update,name='employee_update'),
    path('assets/', views.list_assets, name='list_assets'),
    path('assets/add/', views.register_asset, name='register_asset'),
    path('assets/edit/<int:id>/', views.update_asset, name='update_asset'),
    path('sales-report/', views.sales_report, name='sales_report'),
    path('bookings-report/',views.booking_report,name='booking_report'),
    path('expense-report/',views.expense_report,name='expense_report'),
    path('customer-report/', views.customer_report, name='customer_report'),
    path('supplier-report/', views.supplier_report, name='supplier_report'),
    path('departure-report/', views.departure_report, name='departure_report'),
    path('assets-report/', views.assets_report, name='assets_report'),
    path('income-statement/', views.income_statement, name='income_statement'),
    

]
