# Generated by Django 5.0.4 on 2024-05-31 06:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_name", models.CharField(max_length=255)),
                ("purchase_date", models.DateField()),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("phone", models.CharField(max_length=15)),
                ("reference_name", models.CharField(max_length=80)),
                ("reference_phone", models.CharField(max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("title", models.CharField(max_length=50)),
                ("profile_photo", models.ImageField(upload_to="profile_pics/")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("rent", "Rent"),
                            ("utilities", "Utilities"),
                            ("supplies", "Supplies"),
                            ("salary", "Salary"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField(blank=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank", "Bank"),
                            ("evc_plus", "EVC Plus"),
                            ("edahab", "Edahab"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank", "Bank"),
                            ("evc_plus", "EVC Plus"),
                            ("edahab", "Edahab"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TicketBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passenger_name", models.CharField(max_length=100)),
                ("pnr", models.CharField(max_length=50)),
                (
                    "age_category",
                    models.CharField(
                        choices=[("ADT", "Adult"), ("CHD", "Child")], max_length=3
                    ),
                ),
                ("travel_date", models.DateField()),
                ("fare", models.DecimalField(decimal_places=2, max_digits=9)),
                ("commission", models.DecimalField(decimal_places=2, max_digits=9)),
                ("tax", models.DecimalField(decimal_places=2, max_digits=9)),
                ("sell_fare", models.DecimalField(decimal_places=2, max_digits=9)),
                ("phone", models.CharField(max_length=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("canceled", "Canceled"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("ticket", "Ticket"), ("visa", "Visa")], max_length=10
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank", "Bank"),
                            ("evc_plus", "EVC Plus"),
                            ("edahab", "Edahab"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("partial", "Partial"),
                            ("paid", "Paid"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisaBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("nationality", models.CharField(default="SOMALIA", max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("departure_date", models.DateField()),
                (
                    "visa_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("phone", models.CharField(max_length=15)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="applicant_photos/"
                    ),
                ),
                (
                    "passport_copy",
                    models.FileField(
                        blank=True, null=True, upload_to="passport_copies/"
                    ),
                ),
                (
                    "age_group",
                    models.CharField(
                        choices=[("ADT", "Adult"), ("CHD", "Child"), ("inf", "INF")],
                        max_length=3,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("canceled", "Canceled"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
