# Generated by Django 5.0.4 on 2024-06-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Agency", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
