# Generated by Django 5.0.4 on 2024-06-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Agency", "0003_city_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("nationality", models.CharField(max_length=100)),
            ],
        ),
    ]
