# Generated by Django 5.0.4 on 2024-06-30 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Agency", "0004_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visabooking",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visa_country",
                to="Agency.country",
            ),
        ),
        migrations.AlterField(
            model_name="visabooking",
            name="nationality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visa_nationality",
                to="Agency.country",
            ),
        ),
    ]
